# Generated by Django 4.2.27 on 2026-01-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='目录名称')),
                ('level', models.IntegerField(default=1, verbose_name='层级')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_directories', to='api.directory', verbose_name='父级目录')),
            ],
            options={
                'verbose_name': '目录',
                'verbose_name_plural': '目录',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='接口名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=255, verbose_name='接口路径')),
                ('schema', models.JSONField(blank=True, default=dict, verbose_name='接口定义')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='api.directory', verbose_name='所属目录')),
            ],
            options={
                'verbose_name': '接口',
                'verbose_name_plural': '接口',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='请求数据')),
                ('expected_response', models.JSONField(blank=True, default=dict, verbose_name='预期结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='api.interface', verbose_name='所属接口')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'indexes': [models.Index(fields=['interface'], name='api_testcas_interfa_4de7fc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='interface',
            index=models.Index(fields=['directory'], name='api_interfa_directo_aca01e_idx'),
        ),
        migrations.AddIndex(
            model_name='directory',
            index=models.Index(fields=['parent'], name='api_directo_parent__63038f_idx'),
        ),
    ]
