# Generated by Django 4.2.27 on 2026-01-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.TextField(blank=True, verbose_name='用例描述'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='expected_value',
            field=models.JSONField(blank=True, default=dict, verbose_name='期望值'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_field',
            field=models.CharField(blank=True, max_length=100, verbose_name='测试字段'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='预期响应'),
        ),
        migrations.CreateModel(
            name='TestCaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='类型编码')),
                ('description', models.TextField(blank=True, verbose_name='类型描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='api.testcasecategory', verbose_name='父级类型')),
            ],
            options={
                'verbose_name': '测试用例类型',
                'verbose_name_plural': '测试用例类型',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='api.testcasecategory', verbose_name='用例类型'),
        ),
    ]
