# Generated by Django 4.2.27 on 2026-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testcase_description_testcase_expected_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='test_type',
            field=models.CharField(blank=True, choices=[('positive', '正向'), ('negative', '负向'), ('boundary', '边界值'), ('security', '安全性')], max_length=20, null=True, verbose_name='用例类型'),
        ),
    ]
