# Generated by Django 4.2.27 on 2026-02-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testcase_test_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interface',
            constraint=models.UniqueConstraint(fields=('method', 'path'), name='unique_method_path'),
        ),
    ]
