# Generated by Django 4.2.27 on 2026-02-06 16:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_interface_unique_method_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='环境名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='环境代码')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='环境配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试环境',
                'verbose_name_plural': '测试环境',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestExecutionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='批次ID')),
                ('name', models.CharField(max_length=200, verbose_name='批次名称')),
                ('trigger_type', models.CharField(choices=[('web', 'Web UI'), ('api', 'REST API'), ('cli', '命令行'), ('cron', '定时任务')], max_length=20, verbose_name='触发方式')),
                ('executor', models.CharField(blank=True, max_length=100, verbose_name='执行人')),
                ('total_cases', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='通过用例数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('error_cases', models.IntegerField(default=0, verbose_name='错误用例数')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='执行耗时(ms)')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery任务ID')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.environment', verbose_name='执行环境')),
            ],
            options={
                'verbose_name': '测试执行批次',
                'verbose_name_plural': '测试执行批次',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='执行ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '错误')], default='pending', max_length=20, verbose_name='执行状态')),
                ('request_url', models.TextField(verbose_name='请求URL')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_headers', models.JSONField(default=dict, verbose_name='请求头')),
                ('request_body', models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_headers', models.JSONField(blank=True, default=dict, verbose_name='响应头')),
                ('response_body', models.JSONField(blank=True, default=dict, verbose_name='响应体')),
                ('response_time_ms', models.IntegerField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('assertions_passed', models.IntegerField(default=0, verbose_name='通过断言数')),
                ('assertions_failed', models.IntegerField(default=0, verbose_name='失败断言数')),
                ('assertion_details', models.JSONField(blank=True, default=list, verbose_name='断言详情')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('error_traceback', models.TextField(blank=True, verbose_name='错误堆栈')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='执行耗时(ms)')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='api.testexecutionbatch', verbose_name='所属批次')),
                ('parent_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.testexecution', verbose_name='父执行记录')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试执行记录',
                'verbose_name_plural': '测试执行记录',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='testexecutionbatch',
            index=models.Index(fields=['batch_id'], name='api_testexe_batch_i_3a6fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecutionbatch',
            index=models.Index(fields=['-started_at'], name='api_testexe_started_548015_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecutionbatch',
            index=models.Index(fields=['status'], name='api_testexe_status_fe4834_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['execution_id'], name='api_testexe_executi_f78f77_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['test_case', '-started_at'], name='api_testexe_test_ca_cfb151_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['batch', '-started_at'], name='api_testexe_batch_i_4698bf_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['status'], name='api_testexe_status_78cf48_idx'),
        ),
    ]
