# Generated by Django 4.2.27 on 2026-02-09 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_environment_testexecutionbatch_testexecution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('jenkins_job_name', models.CharField(blank=True, max_length=255, verbose_name='Jenkins Job 名称')),
                ('jenkins_server_url', models.URLField(blank=True, verbose_name='Jenkins 服务器地址')),
                ('jenkins_credentials', models.JSONField(blank=True, default=dict, help_text='{"username": "...", "token": "..."}', verbose_name='Jenkins 认证信息')),
                ('cron_expression', models.CharField(blank=True, max_length=100, verbose_name='Cron 表达式')),
                ('is_cron_enabled', models.BooleanField(default=False, verbose_name='启用定时执行')),
                ('notification_config', models.JSONField(blank=True, default=dict, help_text='{"email": {"enabled": false, "recipients": []}, "webhook": {"enabled": false, "url": "", "type": "dingtalk"}}', verbose_name='通知配置')),
                ('trigger_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='触发 Token')),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_plans', to='api.environment', verbose_name='执行环境')),
            ],
            options={
                'verbose_name': '构建计划',
                'verbose_name_plural': '构建计划',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutorMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('hostname', models.CharField(max_length=255, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP 地址')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('os_type', models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('macos', 'macOS')], default='linux', max_length=20, verbose_name='操作系统')),
                ('labels', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('busy', '忙碌')], default='offline', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('jenkins_node_name', models.CharField(blank=True, max_length=255, verbose_name='Jenkins 节点名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '执行机',
                'verbose_name_plural': '执行机',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BuildStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='步骤序号')),
                ('name', models.CharField(max_length=200, verbose_name='步骤名称')),
                ('script', models.TextField(blank=True, verbose_name='执行脚本')),
                ('timeout', models.IntegerField(default=3600, verbose_name='超时秒数')),
                ('on_failure', models.CharField(choices=[('stop', '停止'), ('continue', '继续'), ('retry', '重试')], default='stop', max_length=20, verbose_name='失败策略')),
                ('build_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.buildplan', verbose_name='所属构建计划')),
            ],
            options={
                'verbose_name': '构建步骤',
                'verbose_name_plural': '构建步骤',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='buildplan',
            name='executor_machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_plans', to='api.executormachine', verbose_name='执行机'),
        ),
        migrations.CreateModel(
            name='BuildExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('manual', '手动触发'), ('cron', '定时任务'), ('api', '外部 API'), ('jenkins_webhook', 'Jenkins Webhook')], default='manual', max_length=20, verbose_name='触发方式')),
                ('triggered_by', models.CharField(blank=True, max_length=100, verbose_name='触发人/来源')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('jenkins_build_number', models.IntegerField(blank=True, null=True, verbose_name='Jenkins 构建号')),
                ('jenkins_build_url', models.URLField(blank=True, verbose_name='Jenkins 构建链接')),
                ('log_text', models.TextField(blank=True, verbose_name='构建日志')),
                ('log_file', models.FileField(blank=True, upload_to='build_logs/', verbose_name='日志文件')),
                ('report_type', models.CharField(choices=[('none', '无'), ('allure', 'Allure'), ('junit', 'JUnit')], default='none', max_length=20, verbose_name='报告类型')),
                ('report_url', models.URLField(blank=True, verbose_name='报告链接')),
                ('report_data', models.JSONField(blank=True, default=dict, verbose_name='报告数据')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='执行耗时(ms)')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='Celery 任务ID')),
                ('build_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.buildplan', verbose_name='所属构建计划')),
                ('executor_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_executions', to='api.executormachine', verbose_name='执行机')),
            ],
            options={
                'verbose_name': '构建执行记录',
                'verbose_name_plural': '构建执行记录',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='buildplan',
            index=models.Index(fields=['status'], name='api_buildpl_status_134ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='buildplan',
            index=models.Index(fields=['trigger_token'], name='api_buildpl_trigger_15cc17_idx'),
        ),
        migrations.AddIndex(
            model_name='buildexecution',
            index=models.Index(fields=['build_plan', '-started_at'], name='api_buildex_build_p_967fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='buildexecution',
            index=models.Index(fields=['status'], name='api_buildex_status_fd92fb_idx'),
        ),
        migrations.AddIndex(
            model_name='buildexecution',
            index=models.Index(fields=['-started_at'], name='api_buildex_started_91db02_idx'),
        ),
    ]
