# Generated by Django 4.2.27 on 2026-02-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_testing_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(max_length=500, verbose_name='用例名称'),
        ),
    ]
