# Generated by Django 4.2.27 on 2026-03-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_testcase_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testcases', to='api.directory', verbose_name='所属项目'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['project'], name='api_testcas_project_831b50_idx'),
        ),
    ]
