# Generated by Django 4.2.27 on 2026-03-16 02:08

from django.db import migrations


def backfill_project(apps, schema_editor):
    """为已有用例根据 interface.directory 向上查找根目录，回填 project 字段"""
    TestCase = apps.get_model('api', 'TestCase')
    Directory = apps.get_model('api', 'Directory')

    dir_cache = {d.id: d for d in Directory.objects.all()}

    def find_root(directory_id):
        d = dir_cache.get(directory_id)
        while d and d.parent_id is not None:
            d = dir_cache.get(d.parent_id)
        return d

    updates = []
    for tc in TestCase.objects.select_related('interface').filter(project__isnull=True):
        root = find_root(tc.interface.directory_id)
        if root:
            tc.project_id = root.id
            updates.append(tc)

    if updates:
        TestCase.objects.bulk_update(updates, ['project'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_project_to_testcase'),
    ]

    operations = [
        migrations.RunPython(backfill_project, migrations.RunPython.noop),
    ]
