# Generated by Django 4.2.27 on 2026-04-22 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_backfill_project_on_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('subject', models.CharField(default='{{status_emoji}} [Test Master] {{plan_name}} - {{status_upper}}', max_length=255, verbose_name='邮件主题')),
                ('body', models.TextField(default='══════════════════════════════════════\n  {{status_emoji}} 自动化测试执行报告\n══════════════════════════════════════\n\n【基本信息】\n  构建计划：{{plan_name}}\n  执行结果：{{status_upper}}\n  执行时间：{{timestamp}}\n  执行耗时：{{duration}}\n\n【触发信息】\n  触发方式：{{trigger_type}}\n  触发人员：{{triggered_by}}\n\n【构建详情】\n  Jenkins 链接：{{jenkins_url}}\n  （点击上方链接可查看完整构建日志与测试产物）\n\n──────────────────────────────────────\n  说明：\n  · SUCCESS  — 所有测试步骤执行通过\n  · FAILED   — 存在失败的测试步骤，请及时排查\n  · CANCELLED — 构建被手动取消\n──────────────────────────────────────\n\n此邮件由 Test Master 自动发送，请勿直接回复。\n如有疑问请联系测试团队。\n', verbose_name='邮件正文')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模板')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.RemoveField(
            model_name='buildplan',
            name='jenkins_credentials',
        ),
        migrations.RemoveField(
            model_name='buildplan',
            name='jenkins_server_url',
        ),
        migrations.AddField(
            model_name='buildplan',
            name='environment_variables',
            field=models.JSONField(blank=True, default=list, help_text='[{"key": "FOO", "value": "bar", "secret": false}, ...]', verbose_name='环境变量'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='git_branch',
            field=models.CharField(blank=True, default='main', max_length=100, verbose_name='Git 分支'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='git_credential_id',
            field=models.CharField(blank=True, default='', help_text='Jenkins 中配置的 Credentials ID，如 github-user', max_length=100, verbose_name='Jenkins 凭证 ID'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='git_repo_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Git 仓库地址'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='jenkinsfile_text',
            field=models.TextField(blank=True, default='', verbose_name='Jenkinsfile 文本'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='report_command',
            field=models.TextField(blank=True, verbose_name='报告生成命令'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='report_enabled',
            field=models.BooleanField(default=False, verbose_name='启用报告上传'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='workspace_cleanup',
            field=models.BooleanField(default=True, verbose_name='构建前清理工作空间'),
        ),
        migrations.AddField(
            model_name='directory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='directory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_directories', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='directory',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='项目描述'),
        ),
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environments', to='api.directory', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='environment',
            name='token',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='environment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='executormachine',
            name='jenkins_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Jenkins Token'),
        ),
        migrations.AddField(
            model_name='executormachine',
            name='jenkins_url',
            field=models.URLField(blank=True, verbose_name='Jenkins 服务器地址'),
        ),
        migrations.AddField(
            model_name='executormachine',
            name='jenkins_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Jenkins 用户名'),
        ),
        migrations.AlterField(
            model_name='buildstep',
            name='timeout',
            field=models.IntegerField(default=120, verbose_name='超时秒数'),
        ),
        migrations.CreateModel(
            name='RegistrationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='邀请令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_registration_invites', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('registered_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_via_invite', to=settings.AUTH_USER_MODEL, verbose_name='注册用户')),
            ],
            options={
                'verbose_name': '注册邀请',
                'verbose_name_plural': '注册邀请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '所有者'), ('admin', '管理员'), ('member', '成员'), ('viewer', '观察者')], default='member', max_length=20, verbose_name='角色')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('project', models.ForeignKey(limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.directory', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '项目成员',
                'verbose_name_plural': '项目成员',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['project', 'user'], name='api_project_project_e2a78c_idx')],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
