# Generated by Django 4.2.27 on 2026-03-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_buildplan_jenkins_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplan',
            name='git_branch',
            field=models.CharField(blank=True, default='main', max_length=100, verbose_name='Git 分支'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='git_credential_type',
            field=models.CharField(choices=[('none', '无'), ('ssh', 'SSH Key'), ('token', 'Token')], default='none', max_length=20, verbose_name='Git 凭据类型'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='git_repo_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Git 仓库地址'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='report_command',
            field=models.TextField(blank=True, verbose_name='报告生成命令'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='report_enabled',
            field=models.BooleanField(default=False, verbose_name='启用报告上传'),
        ),
        migrations.AddField(
            model_name='buildplan',
            name='workspace_cleanup',
            field=models.BooleanField(default=True, verbose_name='构建前清理工作空间'),
        ),
    ]
