# Generated by Django 4.2.27 on 2026-03-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_git_report_to_buildplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplan',
            name='environment_variables',
            field=models.JSONField(blank=True, default=list, help_text='[{"key": "FOO", "value": "bar", "secret": false}, ...]', verbose_name='环境变量'),
        ),
    ]
