# Generated by Django 4.2.27 on 2026-03-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_environment_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplan',
            name='jenkinsfile_text',
            field=models.TextField(blank=True, default='', verbose_name='Jenkinsfile 文本'),
        ),
    ]
