# Generated by Django 4.2.27 on 2026-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_jenkinsfile_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('subject', models.CharField(default='{{status_emoji}} [Test Master] {{plan_name}} - {{status_upper}}', max_length=255, verbose_name='邮件主题')),
                ('body', models.TextField(default='构建计划: {{plan_name}}\n构建结果: {{status_upper}}\n触发方式: {{trigger_type}}\n触发人员: {{triggered_by}}\n执行耗时: {{duration}}\nJenkins 链接: {{jenkins_url}}\n执行时间: {{timestamp}}\n\n---\n此邮件由 Test Master 自动发送，请勿回复。\n', verbose_name='邮件正文')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模板')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='buildstep',
            name='timeout',
            field=models.IntegerField(default=120, verbose_name='超时秒数'),
        ),
    ]
