# Generated by Django 4.2.27 on 2026-03-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_email_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildplan',
            name='git_credential_id',
            field=models.CharField(blank=True, default='', help_text='Jenkins 中配置的 Credentials ID，如 github-user', max_length=100, verbose_name='Jenkins 凭证 ID'),
        ),
    ]
