# Generated by Django 4.2.27 on 2026-03-19 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_git_credential_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildplan',
            name='git_credential_type',
        ),
    ]
