# Generated by Django 4.2.27 on 2026-03-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_git_credential_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='token',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='environment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
