# Generated by Django 4.2.27 on 2026-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_environment_token_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(default='══════════════════════════════════════\n  {{status_emoji}} 自动化测试执行报告\n══════════════════════════════════════\n\n【基本信息】\n  构建计划：{{plan_name}}\n  执行结果：{{status_upper}}\n  执行时间：{{timestamp}}\n  执行耗时：{{duration}}\n\n【触发信息】\n  触发方式：{{trigger_type}}\n  触发人员：{{triggered_by}}\n\n【构建详情】\n  Jenkins 链接：{{jenkins_url}}\n  （点击上方链接可查看完整构建日志与测试产物）\n\n──────────────────────────────────────\n  说明：\n  · SUCCESS  — 所有测试步骤执行通过\n  · FAILED   — 存在失败的测试步骤，请及时排查\n  · CANCELLED — 构建被手动取消\n──────────────────────────────────────\n\n此邮件由 Test Master 自动发送，请勿直接回复。\n如有疑问请联系测试团队。\n', verbose_name='邮件正文'),
        ),
    ]
