# Generated by Django 4.2.27 on 2026-03-20 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_update_email_template_default_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='project',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environments', to='api.directory', verbose_name='关联项目'),
        ),
    ]
