/**
 * Custom SVG Icon Set for Vuetify
 *
 * Replaces the heavy @mdi/font (~1.3 MB woff2) with tree-shaken SVG paths
 * from @mdi/js. All existing `mdi-*` icon name references in templates
 * continue to work without any changes.
 */
import { h } from 'vue'
import type { IconSet, IconProps } from 'vuetify'

// ── Project icons (used in templates) ─────────────────────────────
import {
  mdiAccessPoint,
  mdiAccount,
  mdiAccountCircle,
  mdiAccountOutline,
  mdiAlertCircle,
  mdiAlertCircleOutline,
  mdiApi,
  mdiArrowExpandHorizontal,
  mdiArrowLeft,
  mdiArrowRightCircleOutline,
  mdiArrowTopRight,
  mdiBrain,
  mdiCamera,
  mdiChartLine,
  mdiCheckCircle,
  mdiCheckCircleOutline,
  mdiCheckboxBlankCircleOutline,
  mdiChevronDown,
  mdiChevronUp,
  mdiClipboardFlowOutline,
  mdiClipboardListOutline,
  mdiClipboardTextOffOutline,
  mdiClipboardTextOutline,
  mdiClose,
  mdiCloseCircle,
  mdiCloseCircleOutline,
  mdiCodeBraces,
  mdiCodeJson,
  mdiCogOutline,
  mdiConsole,
  mdiContentSave,
  mdiContentSaveOutline,
  mdiCreation,
  mdiDatabaseOff,
  mdiDelete,
  mdiDeleteOutline,
  mdiDotsVertical,
  mdiDragHorizontalVariant,
  mdiDownload,
  mdiEarth,
  mdiEmailEditOutline,
  mdiEmailNewsletter,
  mdiEmailOffOutline,
  mdiEmailOpenOutline,
  mdiEmailOutline,
  mdiEmoticonSadOutline,
  mdiExport,
  mdiEye,
  mdiEyeOffOutline,
  mdiEyeOutline,
  mdiFileChartOutline,
  mdiFileCodeOutline,
  mdiFileCode,
  mdiFileDocumentOutline,
  mdiFileExcelOutline,
  mdiFileImport,
  mdiFlagCheckered,
  mdiFlaskOutline,
  mdiFolder,
  mdiFolderOpen,
  mdiFolderOutline,
  mdiFolderPlus,
  mdiFormatListNumbered,
  mdiHistory,
  mdiLabel,
  mdiLinkVariant,
  mdiLockOutline,
  mdiLogout,
  mdiMagnify,
  mdiMenuRight,
  mdiPencil,
  mdiPencilCircleOutline,
  mdiPencilOutline,
  mdiPlay,
  mdiPlayCircle,
  mdiPlayCircleOutline,
  mdiPlaylistRemove,
  mdiPlus,
  mdiPlusCircle,
  mdiPlusCircleOutline,
  mdiRefresh,
  mdiRocketLaunch,
  mdiRocketLaunchOutline,
  mdiSchoolOutline,
  mdiServer,
  mdiServerNetwork,
  mdiServerOff,
  mdiShieldCheck,
  mdiShieldOutline,
  mdiStopCircleOutline,
  mdiTagOutline,
  mdiTimerOutline,
  mdiTrashCanOutline,
  mdiTestTube,
  mdiTextLong,
  mdiTranslate,
  mdiUpdate,
  mdiViewDashboardOutline,
  mdiWeatherNight,
  mdiWeatherSunny,
} from '@mdi/js'

// ── Vuetify internal icons (used by components like VSelect, VCheckbox, etc.) ──
import {
  mdiArrowDown,
  mdiArrowUp,
  mdiCached,
  mdiCalendar,
  mdiCheck,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiChevronLeft,
  mdiChevronRight,
  mdiCircle,
  mdiEyedropper,
  mdiInformation,
  mdiMenu,
  mdiMenuDown,
  mdiMinus,
  mdiMinusBox,
  mdiPageFirst,
  mdiPageLast,
  mdiPaperclip,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiStar,
  mdiStarHalfFull,
  mdiStarOutline,
  mdiUnfoldMoreHorizontal,
} from '@mdi/js'

// ── Complete icon name → SVG path map ─────────────────────────────
const iconMap: Record<string, string> = {
  // Project icons
  'mdi-access-point': mdiAccessPoint,
  'mdi-account': mdiAccount,
  'mdi-account-circle': mdiAccountCircle,
  'mdi-account-outline': mdiAccountOutline,
  'mdi-alert-circle': mdiAlertCircle,
  'mdi-alert-circle-outline': mdiAlertCircleOutline,
  'mdi-api': mdiApi,
  'mdi-arrow-expand-horizontal': mdiArrowExpandHorizontal,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-right-circle-outline': mdiArrowRightCircleOutline,
  'mdi-arrow-top-right': mdiArrowTopRight,
  'mdi-brain': mdiBrain,
  'mdi-camera': mdiCamera,
  'mdi-chart-line': mdiChartLine,
  'mdi-check-circle': mdiCheckCircle,
  'mdi-check-circle-outline': mdiCheckCircleOutline,
  'mdi-checkbox-blank-circle-outline': mdiCheckboxBlankCircleOutline,
  'mdi-chevron-down': mdiChevronDown,
  'mdi-chevron-up': mdiChevronUp,
  'mdi-clipboard-flow-outline': mdiClipboardFlowOutline,
  'mdi-clipboard-list-outline': mdiClipboardListOutline,
  'mdi-clipboard-text-off-outline': mdiClipboardTextOffOutline,
  'mdi-clipboard-text-outline': mdiClipboardTextOutline,
  'mdi-close': mdiClose,
  'mdi-close-circle': mdiCloseCircle,
  'mdi-close-circle-outline': mdiCloseCircleOutline,
  'mdi-code-braces': mdiCodeBraces,
  'mdi-code-json': mdiCodeJson,
  'mdi-cog-outline': mdiCogOutline,
  'mdi-console': mdiConsole,
  'mdi-content-save': mdiContentSave,
  'mdi-content-save-outline': mdiContentSaveOutline,
  'mdi-creation': mdiCreation,
  'mdi-database-off': mdiDatabaseOff,
  'mdi-delete': mdiDelete,
  'mdi-delete-outline': mdiDeleteOutline,
  'mdi-dots-vertical': mdiDotsVertical,
  'mdi-drag-horizontal-variant': mdiDragHorizontalVariant,
  'mdi-download': mdiDownload,
  'mdi-earth': mdiEarth,
  'mdi-email-edit-outline': mdiEmailEditOutline,
  'mdi-email-newsletter': mdiEmailNewsletter,
  'mdi-email-off-outline': mdiEmailOffOutline,
  'mdi-email-open-outline': mdiEmailOpenOutline,
  'mdi-email-outline': mdiEmailOutline,
  'mdi-emoticon-sad-outline': mdiEmoticonSadOutline,
  'mdi-export': mdiExport,
  'mdi-eye': mdiEye,
  'mdi-eye-off-outline': mdiEyeOffOutline,
  'mdi-eye-outline': mdiEyeOutline,
  'mdi-file-chart-outline': mdiFileChartOutline,
  'mdi-file-chart-off-outline': mdiFileChartOutline, // fallback – no dedicated "off" variant
  'mdi-file-code': mdiFileCode,
  'mdi-file-code-outline': mdiFileCodeOutline,
  'mdi-file-document-outline': mdiFileDocumentOutline,
  'mdi-file-excel-outline': mdiFileExcelOutline,
  'mdi-file-import': mdiFileImport,
  'mdi-flag-checkered': mdiFlagCheckered,
  'mdi-flask-outline': mdiFlaskOutline,
  'mdi-folder': mdiFolder,
  'mdi-folder-open': mdiFolderOpen,
  'mdi-folder-outline': mdiFolderOutline,
  'mdi-folder-plus': mdiFolderPlus,
  'mdi-format-list-numbered': mdiFormatListNumbered,
  'mdi-history': mdiHistory,
  'mdi-jenkins': mdiServer, // Jenkins icon not in @mdi/js; use server as fallback
  'mdi-label': mdiLabel,
  'mdi-link-variant': mdiLinkVariant,
  'mdi-lock-outline': mdiLockOutline,
  'mdi-logout': mdiLogout,
  'mdi-magnify': mdiMagnify,
  'mdi-menu-right': mdiMenuRight,
  'mdi-pencil': mdiPencil,
  'mdi-pencil-circle-outline': mdiPencilCircleOutline,
  'mdi-pencil-outline': mdiPencilOutline,
  'mdi-play': mdiPlay,
  'mdi-play-circle': mdiPlayCircle,
  'mdi-play-circle-outline': mdiPlayCircleOutline,
  'mdi-playlist-remove': mdiPlaylistRemove,
  'mdi-plus': mdiPlus,
  'mdi-plus-circle': mdiPlusCircle,
  'mdi-plus-circle-outline': mdiPlusCircleOutline,
  'mdi-refresh': mdiRefresh,
  'mdi-rocket-launch': mdiRocketLaunch,
  'mdi-rocket-launch-outline': mdiRocketLaunchOutline,
  'mdi-school-outline': mdiSchoolOutline,
  'mdi-server': mdiServer,
  'mdi-server-network': mdiServerNetwork,
  'mdi-server-off': mdiServerOff,
  'mdi-shield-check': mdiShieldCheck,
  'mdi-shield-outline': mdiShieldOutline,
  'mdi-stop-circle-outline': mdiStopCircleOutline,
  'mdi-tag-outline': mdiTagOutline,
  'mdi-timer-outline': mdiTimerOutline,
  'mdi-trash-can-outline': mdiTrashCanOutline,
  'mdi-test-tube': mdiTestTube,
  'mdi-text-long': mdiTextLong,
  'mdi-translate': mdiTranslate,
  'mdi-update': mdiUpdate,
  'mdi-view-dashboard-outline': mdiViewDashboardOutline,
  'mdi-weather-night': mdiWeatherNight,
  'mdi-weather-sunny': mdiWeatherSunny,

  // Vuetify internal icons
  'mdi-arrow-down': mdiArrowDown,
  'mdi-arrow-up': mdiArrowUp,
  'mdi-cached': mdiCached,
  'mdi-calendar': mdiCalendar,
  'mdi-check': mdiCheck,
  'mdi-checkbox-blank-outline': mdiCheckboxBlankOutline,
  'mdi-checkbox-marked': mdiCheckboxMarked,
  'mdi-chevron-left': mdiChevronLeft,
  'mdi-chevron-right': mdiChevronRight,
  'mdi-circle': mdiCircle,
  'mdi-eyedropper': mdiEyedropper,
  'mdi-information': mdiInformation,
  'mdi-menu': mdiMenu,
  'mdi-menu-down': mdiMenuDown,
  'mdi-minus': mdiMinus,
  'mdi-minus-box': mdiMinusBox,
  'mdi-page-first': mdiPageFirst,
  'mdi-page-last': mdiPageLast,
  'mdi-paperclip': mdiPaperclip,
  'mdi-radiobox-blank': mdiRadioboxBlank,
  'mdi-radiobox-marked': mdiRadioboxMarked,
  'mdi-star': mdiStar,
  'mdi-star-half-full': mdiStarHalfFull,
  'mdi-star-outline': mdiStarOutline,
  'mdi-unfold-more-horizontal': mdiUnfoldMoreHorizontal,
}

// ── Vuetify aliases (internal component icons) ────────────────────
export const svgAliases: Record<string, string> = {
  collapse: mdiChevronUp,
  complete: mdiCheck,
  cancel: mdiCloseCircle,
  close: mdiClose,
  delete: mdiCloseCircle,
  clear: mdiCloseCircle,
  success: mdiCheckCircle,
  info: mdiInformation,
  warning: mdiAlertCircle,
  error: mdiCloseCircle,
  prev: mdiChevronLeft,
  next: mdiChevronRight,
  checkboxOn: mdiCheckboxMarked,
  checkboxOff: mdiCheckboxBlankOutline,
  checkboxIndeterminate: mdiMinusBox,
  delimiter: mdiCircle,
  sortAsc: mdiArrowUp,
  sortDesc: mdiArrowDown,
  expand: mdiChevronDown,
  menu: mdiMenu,
  subgroup: mdiMenuDown,
  dropdown: mdiMenuDown,
  radioOn: mdiRadioboxMarked,
  radioOff: mdiRadioboxBlank,
  edit: mdiPencil,
  ratingEmpty: mdiStarOutline,
  ratingFull: mdiStar,
  ratingHalf: mdiStarHalfFull,
  loading: mdiCached,
  first: mdiPageFirst,
  last: mdiPageLast,
  unfold: mdiUnfoldMoreHorizontal,
  file: mdiPaperclip,
  plus: mdiPlus,
  minus: mdiMinus,
  calendar: mdiCalendar,
  treeviewCollapse: mdiMenuDown,
  treeviewExpand: mdiMenuRight,
  eyeDropper: mdiEyedropper,
}

// ── Custom Icon Set ───────────────────────────────────────────────
export const mdiSvgSet: IconSet = {
  component: (props: IconProps) => {
    const iconName = props.icon as string
    const svgPath = iconMap[iconName] ?? iconName // iconName might already be an SVG path from alias

    // If it looks like an SVG path (starts with M and contains numbers), render it
    const isPath = svgPath.length > 10 && svgPath.startsWith('M')

    if (!isPath) {
      // Unknown icon – render an empty placeholder to avoid crashes
      return h(props.tag, [
        h(
          'svg',
          {
            class: 'v-icon__svg',
            xmlns: 'http://www.w3.org/2000/svg',
            viewBox: '0 0 24 24',
            role: 'img',
            'aria-hidden': true,
          },
          [h('path', { d: '' })]
        ),
      ])
    }

    return h(props.tag, [
      h(
        'svg',
        {
          class: 'v-icon__svg',
          xmlns: 'http://www.w3.org/2000/svg',
          viewBox: '0 0 24 24',
          role: 'img',
          'aria-hidden': true,
        },
        [h('path', { d: svgPath })]
      ),
    ])
  },
}
